export interface ComplianceFormDefinition {
  templatePath: string;
  documentName: string; // stable key used for the document lookup
  originalName: string; // shown to the user
  s3FileName: string; // file name used for temps/ and the s3 key
}

/**
 * Client specific staff profile templates generated by the compliance flow.
 * All templates share the same docxtemplater contract:
 * fullName, fullAddress, dateOfBirth, dbsNumber, appliedFor, experiences[], trainings.<key>.{name,date}
 */
export const complianceFormsList: ComplianceFormDefinition[] = [
  {
    templatePath: './src/assets/profiles/Clarity-Staff-Profile_-_Care_UK_Care_Profile_Template_updated_May_2026.docx',
    documentName: 'ClarityStaffProfile',
    originalName: 'Clarity Staff Profile.docx',
    s3FileName: 'Clarity Staff Profile.docx',
  },
  {
    templatePath: './src/assets/profiles/Eden_Future_Clarity_Staff_Profile_2025.docx',
    documentName: 'EdenFutureClarityStaffProfile',
    originalName: 'Eden Future Clarity Staff Profile.docx',
    s3FileName: 'Eden Future Clarity Staff Profile.docx',
  },
  {
    templatePath: './src/assets/profiles/MID056_BestLives_Staff_Profile_V2_Oct_2025.docx',
    documentName: 'BestLivesStaffProfile',
    originalName: 'BestLives Staff Profile.docx',
    s3FileName: 'BestLives Staff Profile.docx',
  },
  {
    templatePath: './src/assets/profiles/Swanton_Clarity_Staff_Profile.docx',
    documentName: 'SwantonClarityStaffProfile',
    originalName: 'Swanton Clarity Staff Profile.docx',
    s3FileName: 'Swanton Clarity Staff Profile.docx',
  },
];
